/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_5sem;

import java.awt.BorderLayout;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Marvin Siles
 */
public class Categoria_Roles extends javax.swing.JPanel {

    /**
     * Creates new form Categoria_Roles
     */
    private static final Logger logger = LoggerFactory.getLogger(Categoria_Roles.class);
    public Categoria_Roles() {
        initComponents();
        logger.info("Inicializando panel Categoria_Roles...");

        Roles rl = new Roles();
        rl.setSize(750,430);
        rl.setLocation(0,0);
        contenRoles.removeAll();
        contenRoles.add(rl,BorderLayout.CENTER);
        contenRoles.revalidate();
        contenRoles.repaint();
        logger.info("Panel 'Roles' cargado por defecto.");

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenRoles = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(75, 99, 130));

        javax.swing.GroupLayout contenRolesLayout = new javax.swing.GroupLayout(contenRoles);
        contenRoles.setLayout(contenRolesLayout);
        contenRolesLayout.setHorizontalGroup(
            contenRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenRolesLayout.setVerticalGroup(
            contenRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(166, 136, 104));
        jButton1.setText("Roles ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(166, 136, 104));
        jButton2.setText("Categorias de Equipos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(166, 136, 104));
        jButton3.setText("Marcas de Equipos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenRoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(0, 367, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(contenRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        logger.info("Botón 'Roles' presionado.");
        Roles rl = new Roles();
        rl.setSize(750,430);
        rl.setLocation(0,0);
        contenRoles.removeAll();
        contenRoles.add(rl,BorderLayout.CENTER);
        contenRoles.revalidate();
        contenRoles.repaint();
        logger.debug("Panel 'Roles' agregado al contenedor.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        logger.info("Botón 'Categorias de Equipos' presionado.");
        Categoriaa sl = new Categoriaa();
        sl.setSize(750,430);
        sl.setLocation(0,0);
        contenRoles.removeAll();
        contenRoles.add(sl,BorderLayout.CENTER);
        contenRoles.revalidate();
        contenRoles.repaint();
        logger.debug("Panel 'Categoriaa' agregado al contenedor.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        logger.info("Botón 'Marcas de Equipos' presionado.");
        Marcas mc = new  Marcas();
        mc.setSize(750,430);
        mc.setLocation(0,0);
        contenRoles.removeAll();
        contenRoles.add(mc,BorderLayout.CENTER);
        contenRoles.revalidate();
        contenRoles.repaint();
        logger.debug("Panel 'Marcas' agregado al contenedor.");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenRoles;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
